// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWMJLNE1Mai1ZfTtWRxOxxzbWLK-hgOdQ',
    appId: '1:510502217190:android:5845f10dffde554fb4e227',
    messagingSenderId: '510502217190',
    projectId: 'g6app-5fad9',
    storageBucket: 'g6app-5fad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtjAmG9ELD76ojI-0mAuuWl6KPrKlUdBY',
    appId: '1:510502217190:ios:3fa9d87145bd0c29b4e227',
    messagingSenderId: '510502217190',
    projectId: 'g6app-5fad9',
    storageBucket: 'g6app-5fad9.appspot.com',
    androidClientId: '510502217190-3jb8cupg7brvuoa2erupunhs3qrqjdfr.apps.googleusercontent.com',
    iosClientId: '510502217190-2pmh6gvqhhro2ambphb0n69lo4tj63bd.apps.googleusercontent.com',
    iosBundleId: 'pe.exampleg6.notificationsappg6',
  );
}
